import type { BlogPost } from "./types";

export const blogPosts: BlogPost[] = [
  {
    slug: "stop-writing-automations-start-designing-systems",
    title: "Stop Writing Automations. Start Designing Systems.",
    description: "Why linear, Zapier-style chains crack in production, and how AI agents plus systems thinking build automation that holds up.",
    author: "Thomas Guthrie",
    date: "2026-03-29",
    published: true,
    coverImage: {
      src: "https://images.unsplash.com/photo-1556761175-5973dc0f32e7?auto=format&fit=crop&w=1920&q=80",
      alt: "Team collaborating around a laptop, discussing processes and systems",
    },
    cta: { label: "Build your first agent in Runwise", href: "/signup" },
    paragraphs: [
      "For a decade, the dominant story in software automation was simple: connect A to B, add a filter, hit publish. Tools like Zapier, Make, and their peers made that story accessible to people who never wanted to read an API doc. At their best, they removed drudgery and gave small teams enterprise-shaped leverage. At their worst, they trained a generation to think in sequence: if this trigger fires, then run these steps, then maybe wait, then branch. That mental model is not wrong for quick wins. It is incomplete for anything that must survive contact with real customers, messy data, shifting compliance rules, and teams that change their minds every quarter.",
      "When you only write automations, you optimize for the happy path. You draw a diagram from left to right. You celebrate when the test sheet checks green. Then the edge case arrives: the CRM returns a duplicate, the inbox thread splits in two, a human is on vacation, a discount code expires mid-run, or the legal team wants an audit trail nobody planned for. Your automation does not fail gracefully. It fails loudly, or worse, it fails without telling anyone. The fix is usually another zap, then another branch, then another fifty lines of conditional logic that nobody truly owns. Over time the organization stops trusting the stack, and the original builder becomes a bottleneck.",
      "Writing automations piece by piece is like writing procedures without ever naming the role that performs them. You accumulate steps without a stable owner, without shared context, and without a way to reason about the whole. Designing systems is different. A system has boundaries, inputs, outputs, responsibilities, and feedback loops. It treats exceptions as part of the design, not surprises that arrive on a Friday at five. It asks who decides when the machine should pause, who gets notified, what good looks like a month later, and how you will know when the environment changed enough that the system needs a deliberate update.",
      "This is where the shift from traditional workflow tools to AI agents matters for operators who care about durability. A linear workflow tool answers a narrow question: what fixed steps should fire after event X? An agent-oriented platform answers a broader one: what outcome are we trying to secure, what tools and data can we trust, and how should the software behave when reality does not match the spec? The shift is not hype for its own sake. It is a practical requirement if you want automation that outlasts the first vendor API change, the first rebrand of a field name, or the first time a human needs to intervene without breaking the entire chain.",
      "Agents, in the practical sense we care about, are systems that can interpret intent, choose actions within guardrails, and surface uncertainty instead of hiding it. They are not magic. They need clear goals, access policies, and human checkpoints where the stakes are high. What they change is the starting point. Instead of the builder spending hours mapping every branch before anything ships, the builder describes the system in language stakeholders already use, then tightens permissions and behavior until the system earns trust. The work moves from wiring to governance: what is allowed, what is logged, what requires approval, and what happens when the model is unsure.",
      "That is why at Runwise we care less about whether you can draw fifty boxes than whether you can state the job to be done in a sentence a salesperson and an operator both understand. Natural language is not a gimmick here. It is friction reduction at the boundary where most automation projects actually die: between the person who knows the process and the person who has to translate it into brittle configuration. When that translation layer shrinks, you get faster iteration, fewer silent mismatches between intent and implementation, and a clearer path for the next teammate who inherits the system six months from now.",
      "Compare two approaches side by side on a real week of work. In the classic workflow model, each new integration is a project. Each change from another team becomes a ticket. Knowledge lives in scattered zaps, spreadsheets, Slack threads, and the head of whoever built the original chain. Debugging means replaying steps in your head and hoping the third-party service still behaves the way it did last Tuesday. In a system-first model backed by agents, the same integration work still exists, because reality still has APIs and auth and rate limits. The difference is that the living description of what the system must do can sit where people collaborate. The agent executes and explains. Humans review when needed. Iteration focuses on outcomes and risk, not reconnecting the same broken pipe for the third time because a dropdown option changed its internal value.",
      "Search engines and buyers alike are getting sharper about this distinction. Queries that used to stop at how to connect X to Y are expanding into how to run an always-on assistant across my stack, how to audit what an AI did last week, and how to keep customer data inside approved boundaries. If your content strategy still sells point-to-point plumbing as the whole story, you will win some transactional traffic and lose the conversations where budgets actually move. Thought leadership here means being explicit: linear workflows solve tasks. Agentic systems, designed well, support how work really runs. SEO is not separate from that honesty. The phrases people type are a map of the gap between what they have and what they need.",
      "None of this argues against small automations. Every team should ship quick wins. The argument is against stopping there and pretending a chain of triggers equals strategy. The strongest operators we talk to treat early automations as probes. They learn where time disappears, where errors cluster, and where customers feel the seams between tools. Then they promote the survivors into a system that has names, owners, and review paths. Sometimes that system still includes classic workflow apps as components. That is fine. The architecture is what graduates, not the brand on each box.",
      "If you lead a team, the practical question is what you standardize next. Do you reward whoever patches the fastest, or do you invest in a shared language for goals, tools, and guardrails? Do you measure success by how many zaps ran, or by whether the customer got the right answer without a manual rescue? Do you celebrate integrations shipped, or outcomes sustained? Those metrics pull you toward systems design whether you use our product or not. The market is simply running out of patience for heroics that do not compound.",
      "Runwise exists for people who have already felt that limit. It is a generative workflow builder: you describe outcomes, connect the tools you rely on, review what the system proposes, and launch agents that run on your rules. You get visibility into what ran, not a black box that only your most technical teammate can debug. You move from writing another automation to designing a system your organization can argue about, improve, and trust. The point is not to replace human judgment. It is to put judgment in the right places: upfront when you define the job, and at the edges when the world misbehaves, instead of scattered across every brittle branch you never documented.",
      "Security and procurement teams are right to ask hard questions about AI in operations. A serious approach to agents treats credentials, scopes, and logging as first-class concerns, not afterthoughts pasted on at the end of a demo. When you design a system, you can answer those questions in plain language: which systems may be touched, what data may leave which boundary, who can approve exceptions, and what record exists when something unusual happens. That is harder to fake than a slick trigger list, and it is the kind of substance that turns a pilot into a standard.",
      "The economic case is also blunt. Every hour spent maintaining a fragile chain is an hour not spent improving the product, serving a customer, or closing a loop on quality. When your automation stack grows linearly with headcount, you have accidentally built a second product nobody wanted. When your stack grows with clarity of purpose, you buy back time that compounds. Agents do not remove the need for discipline. They change where discipline shows up: less in memorizing field IDs, more in stating outcomes, setting limits, and reviewing runs like you would review any other operational surface.",
      "If you are coming from a Zapier-style mindset, the habit to break is the reflex to start with the trigger. Try starting with the promise instead: what does done mean, who cares, and what would make us stop and ask a human? Pick one narrow workflow you already run by hand more often than you admit. Name the tools honestly. Write the success criteria in one short paragraph a new hire could read. That exercise is the beginning of system design, and it is the same exercise you will repeat inside Runwise when you turn description into something executable.",
      "If you have read this far, you already suspect your next step is not another one-off integration. It is your first coherent agent: one job, clear tools, explicit limits, and a human in the loop where it matters. That is exactly what we built for. Stop writing automations that you will replace in six months. Start designing a system that your team can name. Build your first agent in Runwise today.",
    ],
  },
];

export function getPublishedPosts(): BlogPost[] {
  return [...blogPosts].filter((p) => p.published).sort((a, b) => b.date.localeCompare(a.date));
}

/** Full archive: every post in `blogPosts`, newest first (published and unpublished). */
export function getAllPostsChronological(): BlogPost[] {
  return [...blogPosts].sort((a, b) => b.date.localeCompare(a.date));
}

export function getPostBySlug(slug: string): BlogPost | undefined {
  const post = blogPosts.find((p) => p.slug === slug);
  if (!post?.published) return undefined;
  return post;
}
